"""Udpdate API Key

Revision ID: 2591402acdfb
Revises: bfe55c75f226
Create Date: 2025-04-22 13:05:01.709400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2591402acdfb'
down_revision: Union[str, None] = 'bfe55c75f226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('hashed_key', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('key_prefix', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_api_keys_key_value', table_name='api_keys')
    op.create_index('ix_api_keys_hashed_key', 'api_keys', ['hashed_key'], unique=False)
    op.drop_column('api_keys', 'key_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_value', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('ix_api_keys_hashed_key', table_name='api_keys')
    op.create_index('ix_api_keys_key_value', 'api_keys', ['key_value'], unique=False)
    op.drop_column('api_keys', 'last_used_at')
    op.drop_column('api_keys', 'key_prefix')
    op.drop_column('api_keys', 'hashed_key')
    # ### end Alembic commands ###
